version: "3.9"

services:
  my_site:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./my_site:/my_site
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
